### ISSUE TITLE
Failed to download action 'https://api.github.com/repos/actions/ansible-playbook-docker-action/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by marcosnr** [saubermacherag/ansible-playbook-docker-action#4]
👋  I tried to use your action in the market place:
```
deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/ansible-playbook-docker-action@2.8.5
        with:
          playbookName: 'site.yml'
```
also using: `actions/ansible-playbook-docker-action@master `

for both received this output:
###Download action repository 'actions/ansible-playbook-docker-action@master'
##[warning]Failed to download action 'https://api.github.com/repos/actions/ansible-playbook-docker-action/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 19.661 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/ansible-playbook-docker-action/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 21.691 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).

**Comment by ppoetz** [comment]
Hi,

Thanks for using our action.
It seems there's a bug in my README.md

2.8.5 is not the the right version.
Please use `v1.3` or one of the releases listed here: https://github.com/saubermacherag/ansible-playbook-docker-action/releases

And it seems you're missing the checkout step before using this action.
Please see example below:

```
...
deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jenkins Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Deploy Jenkins Pre-Instance
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_FORCE_COLOR: true
        with:
          playbookName: "path/to/play.yml"
...
```

hth,
Patrick
